<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NahirJamal" failures="11" tests="12" name="Test" time="190.351" errors="0" timestamp="2022-06-23T15:20:57 EET">
  <testcase classname="Pages.EditOrder_In_Yashry" name="CheckThat_someFields_Disabled" time="0.23"/>
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_WithInsert_NegativeNumber_In_OrderDiscount" time="0.155">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderDiscount(EditOrder_In_Yashry.java:392)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_WithInsert_NegativeNumber_In_OrderDiscount -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_WithInsert_NegativeNumber_In_OrderShipping" time="0.042">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderShipping(EditOrder_In_Yashry.java:223)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_WithInsert_NegativeNumber_In_OrderShipping -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_WithInsert_NegativeNumber_In_OrderTotal" time="0.041">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderTotal(EditOrder_In_Yashry.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_WithInsert_NegativeNumber_In_OrderTotal -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal" time="0.053">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal(EditOrder_In_Yashry.java:518)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal" time="0.046">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal(EditOrder_In_Yashry.java:349)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_With_Insert_Zero_In_OrderDiscount" time="0.04">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderDiscount(EditOrder_In_Yashry.java:476)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_With_Insert_Zero_In_OrderDiscount -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_With_Insert_Zero_In_OrderShipping" time="0.039">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderShipping(EditOrder_In_Yashry.java:307)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_With_Insert_Zero_In_OrderShipping -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_With_Insert_Zero_In_OrderTotal" time="0.122">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderTotal(EditOrder_In_Yashry.java:180)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_With_Insert_Zero_In_OrderTotal -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_Without_InsertData_In_OrderDiscount" time="0.065">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderDiscount(EditOrder_In_Yashry.java:434)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_Without_InsertData_In_OrderDiscount -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_Without_InsertData_In_OrderShipping" time="0.07">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderShipping(EditOrder_In_Yashry.java:265)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_Without_InsertData_In_OrderShipping -->
  <testcase classname="Pages.EditOrder_In_Yashry" name="ValidData_Without_InsertData_In_OrderTotal" time="0.034">
    <failure type="java.lang.AssertionError" message="expected [713982] but found [714688]">
      <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at Pages.EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderTotal(EditOrder_In_Yashry.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidData_Without_InsertData_In_OrderTotal -->
</testsuite> <!-- Test -->
